### ISSUE TITLE
Unble to Find Acs Nuget Package

### ISSUE THREAD

**Issue by CherryVikram** [managedcoder/ACSAgentHub#3]
i followed the instructions in the readme file there isn't any ACS Connector hub in nuget and localfeed folder please help me

**Comment by managedcoder** [comment]
Can you add `-showCommands true` to the `deploy_and_configure.ps1` command in Step 2 of the README?  This will print a trace of the deployment commands as they execute with fully expanded argument values and that will help in understanding what's happening.  You can see the path to the folder that the .nupkg will be created in [here](https://github.com/managedcoder/ACSAgentHub/blob/master/Deployment/Scripts/deploy_acs_agent_hub.ps1) on line 113 and it's copied from that folder to the local package folder.  The `-showCommands true` argument also helps by letting you see the commands and you can copy and paste the problematic one into PowerShell to rerun the failing command after remediating and once you get it working, you'll know you have that issue remediated and then you can start fresh again rerun the script until you get a clean run.

**Comment by guitarguySD** [comment]
I also see this problem. the folder localFeed does not exist. 

![image](https://user-images.githubusercontent.com/41213271/180504228-7455498b-e97e-4e5c-9fd3-b4b597515ae4.png)

**Comment by guitarguySD** [comment]
I created the folder ACSAgentHub\ACSConnector\localFeed. 

After deleting all the resources in Azure, I ran the script again and it worked fine (making all the changes noted in #5 ).

**Comment by managedcoder** [comment]
Thanks for reporting this issue.  It was a bug in the script that I've now fixed so I will close this issue.

**Comment by managedcoder** [comment]
@CherryVikram - FYI the ACS Agent Hub bugs have been fixed and overview and walkthrough videos have been added to README doc
