### ISSUE TITLE
From Azure Handoff

### ISSUE THREAD

**Issue by pawelrys** [managedcoder/ACSAgentHub#4]
Hi, could you add some instructions (or the best record a video) on how could connect bot deploying to Azure with ACS Agent Hub? I managed to install locally and connect with Bot Framework Composer chat, but I have some problems with joining Agent with Bot on Azure. 

On the other hand, configuring it locally I have a problem in ChatPanel.tsx file, probably due to the new version @azure module for npm. If you have some time in future you could fix it (I'm totally useless with React).

And to summarise, you did a great project, congratulations!

**Comment by managedcoder** [comment]
Let me look into the ChatPanel issue and I think a screencast of deploying is a good idea and meant to do that

**Comment by aborsato** [comment]
Hi, I am trying to run the code and stepped into the same issues.
The issue with `ChatPanel.tsx` file in my environment was related to the imported dependency `@azure/communication-react` that changed the signature of the method `createAzureCommunicationChatAdapter` to accept an object instead of a list of parameters. This is how I managed to fix the issue:

```TypeScript
                    createAzureCommunicationChatAdapter({
                        endpoint: agentAccessContext.endPoint,
                        displayName: "something here, I guess",
                        threadId: applicationContext!.currentConversation!.threadId,
                        userId: {communicationUserId: applicationContext!.agent!.name},
                        credential: new AzureCommunicationTokenCredential(agentAccessContext.token)
                    }).then(adapter => { 
```

**Comment by guitarguySD** [comment]
Thanks. Yes, also, a great project!

**Comment by managedcoder** [comment]
As @aborsato figured out, the was a breaking change in the ACS UI Toolkit library and I fixed it similarly to what @aborsato suggested and it looks like this now:

`createAzureCommunicationChatAdapter({
                        endpoint: agentAccessContext.endPoint,
                        displayName: applicationContext!.agent!.name,
                        threadId: applicationContext!.currentConversation!.threadId,
                        userId: { communicationUserId: applicationContext!.currentConversation!.agentId },
                        credential: new AzureCommunicationTokenCredential(agentAccessContext.token)
                    }).then(adapter => { `

**Comment by managedcoder** [comment]
@aborsato @dinobrago @pawelrys @lapate - FYI, the ACS Agent Hub bugs have been fixed and overview and walkthrough videos have been added to README doc

**Comment by aborsato** [comment]
I used this project to present a solution to one of our engagements. So, thank you for sharing this code!
