### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by guitarguySD** [managedcoder/ACSAgentHub#5]
I've been working through implementing the Agent Hub.

In the ACSAgentHub.md Readme, there are a couple issues:

- Requires Powershell 7
- Azure CLI extensions - it's unclear in this doc that the extensions are downloaded the first time you run this command. You only need to do this once. 
- I also needed to use az extension add --name webpubsub per issue #1 
- In Step 2 - Deploy ACS Agent Hub there is a typo in the command line. $ngrokFullPath should be -ngrokFullPath

> .\Deployment\Scripts\deploy_and_configure.ps1 -hubName <hub name> -resourceGroup <resource group> $ngrokFullPath <ngrok path> -location <location name> -NuGetFullPath <nuget path>

**Comment by managedcoder** [comment]
I've modified the README to address the issue raised in this issue and believe I've address each of them but if I've missed something, please let me know.
