### ISSUE TITLE
Handoff to human doesn't show conversations

### ISSUE THREAD

**Issue by guitarguySD** [managedcoder/ACSAgentHub#6]
First, awesome piece of work. 

I have the components all up and running and the Agent Hub sees the two requests for handoff to human but the interface doesn't show any other changes. 

I made the change discussed in #4. I refresh the page and see that the conversation count works correctly but the conversations do not show up. Is the React app loading correctly. It looks the same when there are no conversations. In your video, you show the interface with some conversations in place. Does the interface look like the pic here when there are no conversations?

![image](https://user-images.githubusercontent.com/41213271/182479609-1b8d91f3-e8c3-4ff9-9ec1-d6479d730e68.png)

**Comment by managedcoder** [comment]
The conversations are filter based on the agent that is signed in so you have to sign in to see the and it appears if you had not signed in as one of those two agents.  If you sign in you should see the conversations and when you answer one of those two conversations, you will "take ownership" of that conversation and if there were another agent looking at the same list of conversations, they would see the conversation you took ownership disappear (and vice versa if they took ownership of the other conversation).  So the list of conversations will show an agent all the conversations they took ownership of plus all un-owned conversations.  Let me know if that takes care of this issue

**Comment by guitarguySD** [comment]
Ok. Thanks. So I see that it is the Sign In button that is not working for me. I will investigate.
