### ISSUE TITLE
Config changes for publishing to Azure?

### ISSUE THREAD

**Issue by guitarguySD** [managedcoder/ACSAgentHub#7]
I have the entire system running locally with no problems. I'm use the Composer Example bot. I published the Composer Example bot to Azure and the Handoff fails with the error message "An attempt was made to access a socket in a way forbidden by its access permissions."

There are a lot of moving parts so I'm wondering if anyone else has run into this problem. 

Does the acsAgentHubBaseAddress in the bot configuration need to change?

**Comment by managedcoder** [comment]
There are 3 configuration files in this solution:
.\ComposerExample\acsAgentHubBaseAddress\appsettings.json
.\ACSAgentHub\local.settings.json 
.\agent-portal\src\settings\appsettings.ts

You do need to set acsAgentHubBaseAddress in .\ComposerExample\acsAgentHubBaseAddress\appsettings.json to point to your deployed ACSAgentHub.  You will also need to configure .\ACSAgentHub\local.settings.json but the deployment scripts should do most of that for you except for botBaseAddress which I don't think is being used currently but you could set that to your deployed bot.

You will also need to configure .\agent-portal\src\settings\appsettings.ts but the deployment scripts should also set most of this configuration file except for agentHubBaseAddress which should point to your deployed ACSAgentHub.

**Comment by managedcoder** [comment]
@dinobrago, I didn't see any response so I am going to close this issue but I'd be happy to reopen if need be.
